const SUITS=[['S','♠',false],['H','♥',true],['D','♦',true],['C','♣',false]];const RANKS=[['A',1],['2',2],['3',3],['4',4],['5',5],['6',6],['7',7],['8',8],['9',9],['10',10],['J',10],['Q',10],['K',10]];
const $=s=>document.querySelector(s);const app=$('#app');
let state=null, selected=new Set();
function card(id){const suit=SUITS[id[0]], rank=RANKS.find(r=>r[0]===id.slice(1));return{id,s:suit[0],sym:suit[1],red:suit[2],r:rank[0],v:rank[1],ord:RANKS.findIndex(x=>x[0]===rank[0])}}
function deck(){return SUITS.flatMap(s=>RANKS.map(r=>card(s[0]+r[0])))}
function shuffle(a){for(let i=a.length-1;i;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function key(c){return c.s+'-'+c.ord}
function validSeq(cs){if(cs.length<3||new Set(cs.map(c=>c.s)).size!==1)return false;const o=cs.map(c=>c.ord).sort((a,b)=>a-b);if(new Set(o).size!==o.length)return false;for(let i=1;i<o.length;i++)if(o[i]!==o[i-1]+1)return false;return true}
function minimised(hand){const n=hand.length,memo=new Map();const solve=mask=>{if(!mask)return 0;if(memo.has(mask))return memo.get(mask);let i=0;while(!(mask&(1<<i)))i++;let best=hand[i].v;let same=[];for(let j=i+1;j<n;j++)if(mask&(1<<j)&&hand[j].r===hand[i].r)same.push(j);if(same.length>=1)for(const j of same){let nm=mask&~(1<<i)&~(1<<j);best=Math.min(best,solve(nm))}if(same.length>=2)for(let a=0;a<same.length;a++)for(let b=a+1;b<same.length;b++){let nm=mask&~(1<<i)&~(1<<same[a])&~(1<<same[b]);best=Math.min(best,solve(nm))}if(same.length>=3)for(let a=0;a<same.length;a++)for(let b=a+1;b<same.length;b++)for(let c=b+1;c<same.length;c++){let nm=mask&~(1<<i)&~(1<<same[a])&~(1<<same[b])&~(1<<same[c]);best=Math.min(best,solve(nm))}const suit=hand[i].s;for(let start=Math.max(0,hand[i].ord-6);start<=hand[i].ord;start++){let ids=[];for(let o=start;o<n&&o<13;o++){let j=hand.findIndex((c,k)=>k<n&&(mask&(1<<k))&&c.s===suit&&c.ord===o);if(j<0)break;ids.push(j);if(ids.length>=3){let nm=mask;ids.forEach(j=>nm&=~(1<<j));best=Math.min(best,solve(nm))}}}memo.set(mask,best);return best};return solve((1<<n)-1)}
function scoreShow(totals,caller){const min=Math.min(...totals);return totals.map((x,i)=>x===min?0:(i===caller?x+50:x))}
function start(players){const d=shuffle(deck()), hands=players.map(()=>[]);for(let r=0;r<7;r++)players.forEach((_,i)=>hands[i].push(d.pop()));hands[0].push(d.pop());return{players,hands,deck:d,discard:[d.pop()],turn:0,phase:'draw',scores:Array(players.length).fill(0),lastAction:'Game started. Player 1 starts with 8 cards.'}}
function renderLanding(){app.innerHTML=`<div class="shell"><div class="topbar"><div class="brand">MINIMISATION</div><span class="muted small">Card game • 3–6 players</span></div><section class="hero"><div class="panel"><div class="muted">THE LOWEST SCORE WINS</div><h1>Minimise<br>your hand.</h1><p>Build pairs, triplets, quads and same-suit sequences. Every turn, draw one and discard one. Call <b>SHOW</b> when you think your total is the lowest.</p><div class="actions"><button class="btn primary" id="new">Start a game</button><button class="btn secondary" id="rules">How to play</button></div></div><div class="panel"><h3>Quick rules</h3><div class="rules"><div class="rule"><b>7 cards</b><span class="muted small">Everyone ends each turn with 7.</span></div><div class="rule"><b>Pick</b><span class="muted small">Take the exposed discard or blind deck card.</span></div><div class="rule"><b>Make sets</b><span class="muted small">Pairs, 3/4-of-kind, sequences of 3+.</span></div><div class="rule"><b>SHOW</b><span class="muted small">Lowest total gets 0. Wrong caller gets +50.</span></div></div></div></section></div>`;$('#new').onclick=setup;$('#rules').onclick=()=>alert('Goal: minimise your unmatched card value. Ace=1; J/Q/K=10. A-2-3 is valid; Q-K-A is not. At SHOW, all valid combinations are found automatically and only unmatched cards count. If the caller is not tied for lowest, add 50 to the caller’s total.')} 
function setup(){app.innerHTML=`<div class="shell"><div class="topbar"><div class="brand">MINIMISATION</div><span class="muted">New table</span></div><div class="panel" style="max-width:600px;margin:auto"><h2>Create game</h2><p class="muted">This build is a polished pass-and-play MVP. Online room networking is intentionally not faked.</p><div class="field"><label>PLAYER 1</label><input id="p1" value="You" maxlength="18"></div><div id="extra"></div><div class="actions"><button class="btn secondary" id="add">+ Add player</button><button class="btn primary" id="start">Deal cards</button></div></div></div>`;let count=1;$('#add').onclick=()=>{if(count>=6)return;count++;const d=document.createElement('div');d.className='field';d.innerHTML=`<label>PLAYER ${count}</label><input class="pn" value="Player ${count}" maxlength="18">`;$('#extra').appendChild(d);};$('#start').onclick=()=>{if(count<3)return alert('Add at least 3 players.');const names=[$('#p1').value||'Player 1',...Array.from(document.querySelectorAll('.pn')).map(x=>x.value||'Player')];state=start(names);renderGame()}}
function cardHtml(c,i){return `<button class="card ${c.red?'red':''} ${selected.has(c.id)?'selected':''}" data-i="${i}"><span class="rank">${c.r}</span><span class="suit">${c.sym}</span></button>`}
function renderGame(){const me=state.turn===0;const h=state.hands[0];app.innerHTML=`<div class="shell"><div class="topbar"><div class="brand">MINIMISATION</div><div class="muted small">${state.players.length} players · Turn ${state.turn+1}</div></div><div class="game-grid"><section class="table"><div class="opponents">${state.players.slice(1).map((p,i)=>`<div class="opp"><b>${p}</b><div class="muted small">${state.hands[i+1].length} cards</div></div>`).join('')}</div><div class="center"><div><div class="status">${state.lastAction}</div><div style="height:10px"></div><div style="display:flex;gap:14px;justify-content:center"><div class="pile back">★</div><div class="pile">${state.discard.at(-1).r}${state.discard.at(-1).sym}</div></div></div></div><div class="hand">${h.map(cardHtml).join('')}</div></section><aside class="side"><div class="panel"><h3>Your hand</h3><div class="muted small">Estimated minimum: <b>${minimised(h)}</b></div><div class="actions"><button class="btn primary" id="deck">Draw deck</button><button class="btn secondary" id="pick">Pick discard</button></div><div class="actions"><button class="btn danger" id="show">SHOW</button></div><div class="notice small">${state.phase==='draw'?'Choose a card source.':'Select one card to discard.'}</div></div><div class="panel"><h3>Scoreboard</h3>${state.players.map((p,i)=>`<div class="score-row"><span>${i===0?'You':p}</span><b>${state.scores[i]}</b></div>`).join('')}</div></aside></div></div>`;document.querySelectorAll('.card').forEach(b=>b.onclick=()=>{const i=+b.dataset.i;if(state.phase==='discard'){selected.clear();selected.add(h[i].id);renderGame()}});$('#deck').onclick=()=>draw('deck');$('#pick').onclick=()=>draw('discard');$('#show').onclick=show}
function draw(source){if(state.phase!=='draw')return;let c=source==='deck'?state.deck.pop():state.discard.pop();if(!c){alert('Deck exhausted.');return}state.hands[0].push(c);state.phase='discard';state.lastAction=`${source==='deck'?'Blind card drawn.':'Discard picked.'} Select a card to discard.`;renderGame()}
function discard(){if(state.phase!=='discard'||selected.size!==1)return;const id=[...selected][0],h=state.hands[0],i=h.findIndex(c=>c.id===id);const c=h.splice(i,1)[0];state.discard.push(c);selected.clear();state.phase='draw';state.turn=(state.turn+1)%state.players.length;state.lastAction=`${state.players[state.turn]}'s turn.`;if(state.turn!==0)aiTurn();else renderGame()}
function aiTurn(){while(state.turn!==0){const pi=state.turn,h=state.hands[pi];let draw=state.deck.pop();h.push(draw);let worst=h.reduce((a,c,i)=>c.v>a.v?i:a,0);state.discard.push(h.splice(worst,1)[0]);state.turn=(state.turn+1)%state.players.length}renderGame()}
function show(){const totals=state.hands.map(minimised);const scores=scoreShow(totals,0);state.scores=scores;const min=Math.min(...totals);const winner=state.players.filter((_,i)=>totals[i]===min).join(', ');state.lastAction=`SHOW: ${winner} has the lowest total (${min}).`;app.innerHTML=`<div class="shell"><div class="topbar"><div class="brand">MINIMISATION</div><span class="muted">Round complete</span></div><div class="panel"><h1 style="margin-top:0">Results</h1><p class="muted">Lowest achievable totals after automatic combination optimisation.</p>${state.players.map((p,i)=>`<div class="score-row"><span><b>${p}</b><br><span class="muted small">Hand total ${totals[i]}${totals[i]===min?' · LOWEST':''}</span></span><b>${scores[i]} pts</b></div>`).join('')}<div class="actions"><button class="btn primary" id="again">Play again</button><button class="btn secondary" id="home">Home</button></div></div></div>`;$('#again').onclick=()=>{state=start(state.players);renderGame()};$('#home').onclick=renderLanding}
// One-card discard action is delegated here so the side panel can remain simple.
document.addEventListener('click',e=>{if(e.target.closest('#deck')||e.target.closest('#pick')||e.target.closest('#show'))return;if(e.target.closest('.card')&&state?.phase==='discard')setTimeout(discard,0)});
renderLanding();
