const SUITS=[['S','♠',false],['H','♥',true],['D','♦',true],['C','♣',false]];
const RANKS=[['A',1],['2',2],['3',3],['4',4],['5',5],['6',6],['7',7],['8',8],['9',9],['10',10],['J',10],['Q',10],['K',10]];
const $=s=>document.querySelector(s);const app=$('#app');let state=null,selected=new Set();
function card(id){const suit=SUITS.find(s=>s[0]===id[0]),rank=RANKS.find(r=>r[0]===id.slice(1));return{id,s:suit[0],sym:suit[1],red:suit[2],r:rank[0],v:rank[1],ord:RANKS.findIndex(x=>x[0]===rank[0])}}
function deck(){return SUITS.flatMap(s=>RANKS.map(r=>card(s[0]+r[0])))}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function validSet(cs){return cs.length>=2&&cs.length<=4&&new Set(cs.map(c=>c.r)).size===1}
function validSeq(cs){if(cs.length<3||new Set(cs.map(c=>c.s)).size!==1)return false;const o=cs.map(c=>c.ord).sort((a,b)=>a-b);if(new Set(o).size!==o.length)return false;for(let i=1;i<o.length;i++)if(o[i]!==o[i-1]+1)return false;return true}
function validThrow(cs){return cs.length===1||validSet(cs)||validSeq(cs)}
function handTotal(h){return h.reduce((s,c)=>s+c.v,0)}
function scoreShow(totals,caller){const min=Math.min(...totals);return totals.map((x,i)=>x===min?0:(i===caller?x+50:x))}
function start(players){const d=shuffle(deck()),hands=players.map(()=>[]);for(let r=0;r<7;r++)players.forEach((_,i)=>hands[i].push(d.pop()));hands[0].push(d.pop());return{players,hands,deck:d,discard:[],turn:0,phase:'starterDiscard',scores:Array(players.length).fill(0),caller:null,lastAction:`${players[0]} has 8 cards. Discard one to start.`}}
function renderLanding(){app.innerHTML=`<div class="shell"><div class="topbar"><div class="brand">MINIMISATION</div><span class="muted small">♠ 3–6 PLAYERS · CASINO TABLE ♣</span></div><section class="hero"><div class="panel"><div class="muted small">♠ THE LOWEST SCORE WINS ♣</div><h1>Minimise<br>your hand.</h1><p>Pick one card, then throw a single card or a valid pair, triplet, quad or same-suit sequence. Removing combinations reduces both your card count and score.</p><div class="actions"><button class="btn primary" id="new">Start a game</button><button class="btn secondary" id="rules">How to play</button></div></div><div class="panel"><h3>Quick rules</h3><div class="rules"><div class="rule"><b>Opening</b><span class="muted small">Starter gets 8 and discards exactly 1 — no pick.</span></div><div class="rule"><b>Pick 1</b><span class="muted small">Take the exposed discard or one blind deck card.</span></div><div class="rule"><b>Throw sets</b><span class="muted small">Throw 1 card, or a pair/triplet/quad/sequence.</span></div><div class="rule"><b>SHOW</b><span class="muted small">Lowest remaining card value gets 0. Wrong caller gets +50.</span></div></div></div></section></div>`;$('#new').onclick=setup;$('#rules').onclick=()=>alert('Opening: starter has 8 cards and discards exactly one. Normal turn: pick ONE card from the blind deck or exposed discard, then throw ONE card OR a valid pair, triplet, quad or same-suit sequence. The thrown cards leave your hand permanently. SHOW scores the cards still in your hand. Ace=1; J/Q/K=10; A-2-3 is valid, Q-K-A is not.')}
function setup(){app.innerHTML=`<div class="shell"><div class="topbar"><div class="brand">MINIMISATION</div><span class="muted">NEW TABLE</span></div><div class="panel" style="max-width:600px;margin:auto"><h2>Create game</h2><p class="muted">Pass-and-play mode: all players use the same device. Online rooms are not enabled in this build.</p><div class="field"><label>PLAYER 1</label><input id="p1" value="You" maxlength="18"></div><div id="extra"></div><div class="actions"><button class="btn secondary" id="add">+ Add player</button><button class="btn primary" id="start">Deal cards</button></div></div></div>`;let count=1;$('#add').onclick=()=>{if(count>=6)return;count++;const d=document.createElement('div');d.className='field';d.innerHTML=`<label>PLAYER ${count}</label><input class="pn" value="Player ${count}" maxlength="18">`;$('#extra').appendChild(d)};$('#start').onclick=()=>{if(count<3)return alert('Add at least 3 players.');const names=[$('#p1').value.trim()||'Player 1',...Array.from(document.querySelectorAll('.pn')).map(x=>x.value.trim()||'Player')];state=start(names);selected.clear();renderGame()}}
function selectedCards(h){return h.filter(c=>selected.has(c.id))}
function throwLabel(cs){if(cs.length===1)return 'Discard 1 card';if(validSet(cs))return `Throw pair/triplet/quad (${cs.length})`;if(validSeq(cs))return `Throw sequence (${cs.length})`;return 'Invalid combination'}
function cardHtml(c,i){return `<button type="button" class="card ${c.red?'red':''} ${selected.has(c.id)?'selected':''}" data-i="${i}" aria-label="${c.r} of ${c.s}"><span class="rank">${c.r}</span><span class="suit">${c.sym}</span></button>`}
function renderGame(){const h=state.hands[0],current=state.players[state.turn],starter=state.phase==='starterDiscard',canSelect=state.turn===0&&(starter||state.phase==='discard'),top=state.discard.at(-1),sc=selectedCards(h),valid=starter?sc.length===1:validThrow(sc);const actionText=starter?'OPENING DEAL · Discard exactly 1 of your 8':state.phase==='draw'?'YOUR TURN · Pick 1 card':state.phase==='discard'?'YOUR TURN · Throw cards':'ROUND COMPLETE';
app.innerHTML=`<div class="shell"><div class="topbar"><div class="brand">MINIMISATION</div><div class="muted small">${state.players.length} PLAYERS · ${current.toUpperCase()}'S TURN</div></div><div class="game-grid"><section class="table"><div class="opponents">${state.players.slice(1).map((p,i)=>`<div class="opp"><b>${p}</b><div class="muted small">${state.hands[i+1].length} cards</div></div>`).join('')}</div><div class="center"><div class="table-center"><div class="status">${actionText}</div><div class="piles"><div class="pile back" aria-label="Face-down deck"><span>★</span></div><div class="pile ${top?'exposed':'empty'}" aria-label="${top?'Exposed discard':'No discard yet'}">${top?`${top.r}${top.sym}`:'—'}</div></div><div class="pile-labels"><span>BLIND DECK</span><span>${top?'EXPOSED DISCARD':'NO DISCARD'}</span></div></div></div><div class="hand-title"><span>YOUR HAND · ${h.length} CARDS</span><span class="muted small">${starter?'Select exactly ONE card':'Select a card or a complete combination to throw'}</span></div><div class="hand">${h.map(cardHtml).join('')}</div>${canSelect?`<div class="discard-bar"><div class="selection-copy">${sc.length?`Selected ${sc.length}: <b>${sc.map(c=>c.r+c.sym).join(' · ')}</b><br><span class="muted small">${valid?throwLabel(sc):'For multiple cards, select a valid pair/set or sequence'}</span>`:'Select what you want to throw'}</div><button class="btn danger discard-btn" id="discardSelected" ${valid?'':'disabled'}>${starter?'Discard 1 to start':valid?throwLabel(sc):'Select valid cards'}</button></div>`:''}</section><aside class="side"><div class="panel"><h3>Table controls</h3><div class="muted small">Your remaining value: <b>${handTotal(h)}</b> points</div><div class="actions">${state.turn===0&&!starter&&state.phase==='draw'?`<button class="btn primary" id="deck">Pick blind card</button><button class="btn secondary" id="pick" ${!top?'disabled':''}>Pick discard</button>`:state.turn!==0?`<button class="btn secondary" id="next">Next player</button>`:''}</div><div class="actions"><label class="small muted" for="caller">SHOW called by</label><select id="caller">${state.players.map((p,i)=>`<option value="${i}" ${state.turn===i?'selected':''}>${p}</option>`).join('')}</select><button class="btn danger" id="show" ${starter||state.phase==='complete'?'disabled':''}>SHOW</button></div><div class="notice small">${starter?'OPENING: you have 8. Throw exactly one card. Do not pick.':state.phase==='draw'?'Pick exactly ONE card, then choose what to throw.':`You can throw a single card or remove a valid pair, triplet, quad or same-suit sequence. ${sc.length>1?'Multiple selection is active.':''}`}</div></div><div class="panel"><h3>Scoreboard</h3>${state.players.map((p,i)=>`<div class="score-row"><span>${p}</span><b>${state.scores[i]}</b></div>`).join('')}</div></aside></div></div>`;
document.querySelectorAll('.card').forEach(b=>b.onclick=()=>{if(!canSelect)return;const c=h[+b.dataset.i];if(selected.has(c.id))selected.delete(c.id);else selected.add(c.id);renderGame()});if($('#discardSelected'))$('#discardSelected').onclick=discardSelected;if($('#deck'))$('#deck').onclick=()=>draw('deck');if($('#pick'))$('#pick').onclick=()=>draw('discard');if($('#next'))$('#next').onclick=advanceAI;if($('#show'))$('#show').onclick=()=>show(+$('select#caller').value)}
function draw(source){if(state.turn!==0||state.phase!=='draw')return;const c=source==='deck'?state.deck.pop():state.discard.pop();if(!c){alert(source==='deck'?'Deck exhausted.':'There is no exposed discard.');return}state.hands[0].push(c);selected.clear();state.phase='discard';state.lastAction=`${source==='deck'?'Blind card picked.':'Exposed discard picked.'} Choose what to throw.`;renderGame()}
function discardSelected(){if(state.turn!==0||!['starterDiscard','discard'].includes(state.phase))return;const h=state.hands[0],cs=selectedCards(h);if((state.phase==='starterDiscard'&&cs.length!==1)||(state.phase==='discard'&&!validThrow(cs)))return;const ids=new Set(cs.map(c=>c.id));state.hands[0]=h.filter(c=>!ids.has(c.id));state.discard.push(cs[cs.length-1]);for(let i=cs.length-2;i>=0;i--)state.discard.push(cs[i]);selected.clear();if(state.phase==='starterDiscard'){state.phase='draw';state.turn=1;state.lastAction=`${state.players[1]}'s turn. Opening discard is exposed.`;advanceAI();return}state.phase='draw';state.turn=1;state.lastAction=`${state.players[1]}'s turn. Pick one card.`;advanceAI()}
function candidateThrows(h){const out=[];h.forEach(c=>out.push([c]));for(let i=0;i<h.length;i++)for(let j=i+1;j<h.length;j++){const cs=[h[i],h[j]];if(validSet(cs))out.push(cs)}for(let i=0;i<h.length;i++)for(let j=i+1;j<h.length;j++)for(let k=j+1;k<h.length;k++){const cs=[h[i],h[j],h[k]];if(validSet(cs)||validSeq(cs))out.push(cs)}for(let i=0;i<h.length;i++)for(let j=i+1;j<h.length;j++)for(let k=j+1;k<h.length;k++)for(let l=k+1;l<h.length;l++){const cs=[h[i],h[j],h[k],h[l]];if(validSet(cs)||validSeq(cs))out.push(cs)}return out}
function aiBestThrow(h){let best=[h[0]],bestScore=[Infinity,Infinity];for(const cs of candidateThrows(h)){const ids=new Set(cs.map(c=>c.id)),remain=h.filter(c=>!ids.has(c.id)),score=[handTotal(remain),remain.length];if(score[0]<bestScore[0]||(score[0]===bestScore[0]&&score[1]<bestScore[1])){bestScore=score;best=cs}}return best}
function advanceAI(){while(state.turn!==0&&state.phase!=='complete'){const pi=state.turn,h=state.hands[pi],top=state.discard.at(-1);let take=state.deck.pop();if(top){const discardOption=[...h,top],throwWithTop=aiBestThrow(discardOption),scoreWithTop=handTotal(discardOption.filter(c=>!new Set(throwWithTop.map(x=>x.id)).has(c.id)));const throwWithout=aiBestThrow(h),scoreWithout=handTotal(h.filter(c=>!new Set(throwWithout.map(x=>x.id)).has(c.id)));if(scoreWithTop<=scoreWithout){take=state.discard.pop()}}h.push(take);const cs=aiBestThrow(h),ids=new Set(cs.map(c=>c.id));const thrown=h.filter(c=>ids.has(c.id));state.hands[pi]=h.filter(c=>!ids.has(c.id));thrown.forEach(c=>state.discard.push(c));state.turn=(pi+1)%state.players.length;state.phase='draw';state.lastAction=state.turn===0?`${state.players[0]}'s turn. Pick one card.`:`${state.players[state.turn]}'s turn.`}renderGame()}
function show(caller){if(!state||state.phase==='complete'||state.phase==='starterDiscard')return;const totals=state.hands.map(handTotal),scores=scoreShow(totals,caller),min=Math.min(...totals);state.scores=scores;state.caller=caller;state.phase='complete';const winners=state.players.filter((_,i)=>totals[i]===min).join(', ');app.innerHTML=`<div class="shell"><div class="topbar"><div class="brand">MINIMISATION</div><span class="muted">ROUND COMPLETE</span></div><div class="panel"><h1 style="margin-top:0">Results</h1><p class="muted">${state.players[caller]} called SHOW. Lowest remaining card value: <b>${min}</b>.</p>${state.players.map((p,i)=>`<div class="score-row"><span><b>${p}</b><br><span class="muted small">Remaining ${totals[i]}${totals[i]===min?' · LOWEST':''}${i===caller?' · CALLER':''}</span></span><b>${scores[i]} pts</b></div>`).join('')}<p class="muted small">Lowest player(s): ${winners}. Thrown combinations are already removed from each hand. A non-lowest caller receives their remaining total + 50.</p><div class="actions"><button class="btn primary" id="again">Play again</button><button class="btn secondary" id="home">Home</button></div></div></div>`;$('#again').onclick=()=>{state=start(state.players);selected.clear();renderGame()};$('#home').onclick=renderLanding}
renderLanding();
