const SUITS=[['S','♠',false],['H','♥',true],['D','♦',true],['C','♣',false]];
const RANKS=[['A',1],['2',2],['3',3],['4',4],['5',5],['6',6],['7',7],['8',8],['9',9],['10',10],['J',10],['Q',10],['K',10]];
const $=s=>document.querySelector(s);const app=$('#app');
let state=null,selected=new Set();
function card(id){const suit=SUITS.find(s=>s[0]===id[0]),rank=RANKS.find(r=>r[0]===id.slice(1));return{id,s:suit[0],sym:suit[1],red:suit[2],r:rank[0],v:rank[1],ord:RANKS.findIndex(x=>x[0]===rank[0])}}
function deck(){return SUITS.flatMap(s=>RANKS.map(r=>card(s[0]+r[0])))}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function validSet(cs){return cs.length>=2&&cs.length<=4&&new Set(cs.map(c=>c.r)).size===1}
function validSeq(cs){if(cs.length<3||new Set(cs.map(c=>c.s)).size!==1)return false;const o=cs.map(c=>c.ord).sort((a,b)=>a-b);if(new Set(o).size!==o.length)return false;for(let i=1;i<o.length;i++)if(o[i]!==o[i-1]+1)return false;return true}
function minimised(hand){const n=hand.length,full=(1<<n)-1,memo=new Map(),groups=[];for(let mask=1;mask<=full;mask++){const cs=[];for(let i=0;i<n;i++)if(mask&(1<<i))cs.push(hand[i]);if(validSet(cs)||validSeq(cs))groups.push(mask)}const solve=mask=>{if(!mask)return 0;if(memo.has(mask))return memo.get(mask);let first=0;while(!(mask&(1<<first)))first++;let best=hand[first].v;for(const g of groups){if(!(g&(1<<first))||((g&mask)!==g))continue;best=Math.min(best,solve(mask^g))}memo.set(mask,best);return best};return solve(full)}
function scoreShow(totals,caller){const min=Math.min(...totals);return totals.map((x,i)=>x===min?0:(i===caller?x+50:x))}
function start(players){const d=shuffle(deck()),hands=players.map(()=>[]);for(let r=0;r<7;r++)players.forEach((_,i)=>hands[i].push(d.pop()));hands[0].push(d.pop());return{players,hands,deck:d,discard:[d.pop()],turn:0,phase:'starterDiscard',scores:Array(players.length).fill(0),caller:null,lastAction:`${players[0]} has 8 cards. Discard one to start.`}}
function renderLanding(){app.innerHTML=`<div class="shell"><div class="topbar"><div class="brand">MINIMISATION</div><span class="muted small">3–6 PLAYERS · TABLE GAME</span></div><section class="hero"><div class="panel"><div class="muted small">♠  THE LOWEST SCORE WINS  ♣</div><h1>Minimise<br>your hand.</h1><p>Build pairs, triplets, quads and same-suit sequences. Pick one card, discard one, and call SHOW when you think you are lowest.</p><div class="actions"><button class="btn primary" id="new">Start a game</button><button class="btn secondary" id="rules">How to play</button></div></div><div class="panel"><h3>Quick rules</h3><div class="rules"><div class="rule"><b>7 cards</b><span class="muted small">Starter gets 8, then discards first.</span></div><div class="rule"><b>Pick</b><span class="muted small">Take the exposed discard or a blind deck card.</span></div><div class="rule"><b>Make sets</b><span class="muted small">Pairs, 3/4-of-kind, sequences of 3+.</span></div><div class="rule"><b>SHOW</b><span class="muted small">Lowest total gets 0. Wrong caller gets +50.</span></div></div></div></section></div>`;$('#new').onclick=setup;$('#rules').onclick=()=>alert('Goal: minimise unmatched card value. Ace=1; J/Q/K=10. A-2-3 is valid; Q-K-A is not. At SHOW, the system finds the mathematically optimal non-overlapping combinations. Every lowest-tied player scores 0. If the caller is not lowest, add 50 to the caller total.')}
function setup(){app.innerHTML=`<div class="shell"><div class="topbar"><div class="brand">MINIMISATION</div><span class="muted">NEW TABLE</span></div><div class="panel" style="max-width:600px;margin:auto"><h2>Create game</h2><p class="muted">Pass-and-play mode: all players use the same device. Online rooms are not enabled in this build.</p><div class="field"><label>PLAYER 1</label><input id="p1" value="You" maxlength="18"></div><div id="extra"></div><div class="actions"><button class="btn secondary" id="add">+ Add player</button><button class="btn primary" id="start">Deal cards</button></div></div></div>`;let count=1;$('#add').onclick=()=>{if(count>=6)return;count++;const d=document.createElement('div');d.className='field';d.innerHTML=`<label>PLAYER ${count}</label><input class="pn" value="Player ${count}" maxlength="18">`;$('#extra').appendChild(d)};$('#start').onclick=()=>{if(count<3)return alert('Add at least 3 players.');const names=[$('#p1').value.trim()||'Player 1',...Array.from(document.querySelectorAll('.pn')).map(x=>x.value.trim()||'Player')];state=start(names);selected.clear();renderGame()}}
function cardHtml(c,i){return `<button class="card ${c.red?'red':''} ${selected.has(c.id)?'selected':''}" data-i="${i}" aria-label="${c.r} of ${c.s}"><span class="rank">${c.r}</span><span class="suit">${c.sym}</span></button>`}
function renderGame(){const h=state.hands[0],current=state.players[state.turn],starter=state.phase==='starterDiscard';const actionText=starter?'STARTER TURN · Discard 1 of your 8 cards':state.phase==='draw'?'YOUR TURN · Draw 1 card':state.phase==='discard'?'YOUR TURN · Discard 1 card':'ROUND COMPLETE';app.innerHTML=`<div class="shell"><div class="topbar"><div class="brand">MINIMISATION</div><div class="muted small">${state.players.length} PLAYERS · ${current.toUpperCase()}'S TURN</div></div><div class="game-grid"><section class="table"><div class="opponents">${state.players.slice(1).map((p,i)=>`<div class="opp"><b>${p}</b><div class="muted small">${state.hands[i+1].length} cards</div></div>`).join('')}</div><div class="center"><div><div class="status">${actionText}</div><div class="piles"><div class="pile back">★</div><div class="pile">${state.discard.at(-1)?.r||''}${state.discard.at(-1)?.sym||''}</div></div></div></div><div class="hand">${h.map(cardHtml).join('')}</div></section><aside class="side"><div class="panel"><h3>Table controls</h3><div class="muted small">Your minimum: <b>${minimised(h)}</b> points</div><div class="actions">${state.turn===0&&!starter&&state.phase==='draw'?`<button class="btn primary" id="deck">Draw deck</button><button class="btn secondary" id="pick">Pick discard</button>`:state.turn!==0?`<button class="btn secondary" id="next">Next player</button>`:''}</div><div class="actions"><label class="small muted" for="caller">SHOW called by</label><select id="caller">${state.players.map((p,i)=>`<option value="${i}" ${state.turn===i?'selected':''}>${p}</option>`).join('')}</select><button class="btn danger" id="show" ${starter||state.phase==='complete'?'disabled':''}>SHOW</button></div><div class="notice small">${starter?'You were dealt 8 cards to start. Discard exactly one — do not draw.':state.phase==='draw'?'Choose the exposed discard or the blind deck.':state.phase==='discard'?'Select one card from your hand to discard.':'Round complete.'}</div></div><div class="panel"><h3>Scoreboard</h3>${state.players.map((p,i)=>`<div class="score-row"><span>${p}</span><b>${state.scores[i]}</b></div>`).join('')}</div></aside></div></div>`;document.querySelectorAll('.card').forEach(b=>b.onclick=()=>{if(state.turn!==0)return;const i=+b.dataset.i;if(state.phase==='starterDiscard'||state.phase==='discard'){selected.clear();selected.add(h[i].id);renderGame();setTimeout(discard,80)}});if($('#deck'))$('#deck').onclick=()=>draw('deck');if($('#pick'))$('#pick').onclick=()=>draw('discard');if($('#next'))$('#next').onclick=advanceAI;if($('#show'))$('#show').onclick=()=>show(+$('select#caller').value)}
function draw(source){if(state.turn!==0||state.phase!=='draw')return;const c=source==='deck'?state.deck.pop():state.discard.pop();if(!c){alert('Deck exhausted.');return}state.hands[0].push(c);state.phase='discard';state.lastAction=`${source==='deck'?'Blind card drawn.':'Discard picked.'} Select one card to discard.`;renderGame()}
function discard(){if(state.turn!==0||!['starterDiscard','discard'].includes(state.phase)||selected.size!==1)return;const h=state.hands[0],id=[...selected][0],i=h.findIndex(c=>c.id===id);if(i<0)return;const c=h.splice(i,1)[0];state.discard.push(c);selected.clear();state.phase='draw';state.turn=1;state.lastAction=`${state.players[1]}'s turn. Draw one card.`;advanceAI()}
function aiPickIndex(h){let best=0,bestScore=Infinity;for(let i=0;i<h.length;i++){const test=h.filter((_,j)=>j!==i),score=minimised(test);if(score<bestScore||(score===bestScore&&h[i].v>h[best].v)){bestScore=score;best=i}}return best}
function advanceAI(){while(state.turn!==0&&state.phase!=='complete'){const pi=state.turn,h=state.hands[pi],top=state.discard.at(-1),takeDiscard=top&&minimised([...h,top])<minimised(h)+top.v,c=takeDiscard?state.discard.pop():state.deck.pop();if(!c){state.phase='complete';break}h.push(c);const di=aiPickIndex(h);state.discard.push(h.splice(di,1)[0]);state.turn=(pi+1)%state.players.length;state.phase='draw';state.lastAction=state.turn===0?`${state.players[0]}'s turn. Draw one card.`:`${state.players[state.turn]}'s turn.`}renderGame()}
function show(caller){if(!state||state.phase==='complete'||state.phase==='starterDiscard')return;const totals=state.hands.map(minimised),scores=scoreShow(totals,caller),min=Math.min(...totals);state.scores=scores;state.caller=caller;state.phase='complete';const winners=state.players.filter((_,i)=>totals[i]===min).join(', ');app.innerHTML=`<div class="shell"><div class="topbar"><div class="brand">MINIMISATION</div><span class="muted">ROUND COMPLETE</span></div><div class="panel"><h1 style="margin-top:0">Results</h1><p class="muted">${state.players[caller]} called SHOW. Lowest achievable total: <b>${min}</b>.</p>${state.players.map((p,i)=>`<div class="score-row"><span><b>${p}</b><br><span class="muted small">Minimum ${totals[i]}${totals[i]===min?' · LOWEST':''}${i===caller?' · CALLER':''}</span></span><b>${scores[i]} pts</b></div>`).join('')}<p class="muted small">Lowest player(s): ${winners}. A non-lowest caller receives their total + 50.</p><div class="actions"><button class="btn primary" id="again">Play again</button><button class="btn secondary" id="home">Home</button></div></div></div>`;$('#again').onclick=()=>{state=start(state.players);selected.clear();renderGame()};$('#home').onclick=renderLanding}
renderLanding();
